<template>
  <v-autocomplete
    :flat="flat"
    :search="search"
    :type="type"
    :modelValue="modelValue"
    :error="error"
    :reverse="reverse"
    :density="density"
    :maxWidth="maxWidth"
    :minWidth="minWidth"
    :width="width"
    :rounded="rounded"
    :tile="tile"
    :theme="theme"
    :color="color"
    :variant="variant"
    :name="name"
    :autocomplete="autocomplete"
    :disabled="disabled"
    :multiple="multiple"
    :placeholder="placeholder"
    :id="id"
    :prefix="prefix"
    :role="role"
    :autofocus="autofocus"
    :items="items"
    :active="active"
    :baseColor="baseColor"
    :prependIcon="prependIcon"
    :appendIcon="appendIcon"
    :readonly="readonly"
    :loading="loading"
    :label="label"
    :autoSelectFirst="autoSelectFirst"
    :clearOnSelect="clearOnSelect"
    :filterMode="filterMode"
    :noFilter="noFilter"
    :customFilter="customFilter"
    :customKeyFilter="customKeyFilter"
    :filterKeys="filterKeys"
    :chips="chips"
    :closableChips="closableChips"
    :eager="eager"
    :hideNoData="hideNoData"
    :hideSelected="hideSelected"
    :listProps="listProps"
    :bgColor="bgColor"
    :itemTitle="itemTitle"
    :itemValue="itemValue"
    :itemChildren="itemChildren"
    :itemProps="itemProps"
    :itemType="itemType"
    :returnObject="returnObject"
    :valueComparator="valueComparator"
    :menu="menu"
    :menuIcon="menuIcon"
    :menuProps="menuProps"
    :noDataText="noDataText"
    :openOnClear="openOnClear"
    :itemColor="itemColor"
    :noAutoScroll="noAutoScroll"
    :closeText="closeText"
    :openText="openText"
    :counter="counter"
    :persistentPlaceholder="persistentPlaceholder"
    :persistentCounter="persistentCounter"
    :suffix="suffix"
    :centerAffix="centerAffix"
    :glow="glow"
    :iconColor="iconColor"
    :hideSpinButtons="hideSpinButtons"
    :hint="hint"
    :persistentHint="persistentHint"
    :messages="messages"
    :errorMessages="errorMessages"
    :maxErrors="maxErrors"
    :rules="rules"
    :validateOn="validateOn"
    :focused="focused"
    :hideDetails="hideDetails"
    :appendInnerIcon="appendInnerIcon"
    :clearable="clearable"
    :clearIcon="clearIcon"
    :persistentClear="persistentClear"
    :prependInnerIcon="prependInnerIcon"
    :singleLine="singleLine"
    :counterValue="counterValue"
    :modelModifiers="modelModifiers"
  >
    {{ children }}
  </v-autocomplete>
</template>

<script setup>
import { useModelState } from "@pyvuetify/vuetify";

// Reactive state synced with Python
const children = useModelState("children");
const flat = useModelState("flat");
const search = useModelState("search");
const type = useModelState("type");
const modelValue = useModelState("model_value");
const error = useModelState("error");
const reverse = useModelState("reverse");
const density = useModelState("density");
const maxWidth = useModelState("max_width");
const minWidth = useModelState("min_width");
const width = useModelState("width");
const rounded = useModelState("rounded");
const tile = useModelState("tile");
const theme = useModelState("theme");
const color = useModelState("color");
const variant = useModelState("variant");
const name = useModelState("name");
const autocomplete = useModelState("autocomplete");
const disabled = useModelState("disabled");
const multiple = useModelState("multiple");
const placeholder = useModelState("placeholder");
const id = useModelState("id");
const prefix = useModelState("prefix");
const role = useModelState("role");
const autofocus = useModelState("autofocus");
const items = useModelState("items");
const active = useModelState("active");
const baseColor = useModelState("base_color");
const prependIcon = useModelState("prepend_icon");
const appendIcon = useModelState("append_icon");
const readonly = useModelState("readonly");
const loading = useModelState("loading");
const label = useModelState("label");
const autoSelectFirst = useModelState("auto_select_first");
const clearOnSelect = useModelState("clear_on_select");
const filterMode = useModelState("filter_mode");
const noFilter = useModelState("no_filter");
const customFilter = useModelState("custom_filter");
const customKeyFilter = useModelState("custom_key_filter");
const filterKeys = useModelState("filter_keys");
const chips = useModelState("chips");
const closableChips = useModelState("closable_chips");
const eager = useModelState("eager");
const hideNoData = useModelState("hide_no_data");
const hideSelected = useModelState("hide_selected");
const listProps = useModelState("list_props");
const bgColor = useModelState("bg_color");
const itemTitle = useModelState("item_title");
const itemValue = useModelState("item_value");
const itemChildren = useModelState("item_children");
const itemProps = useModelState("item_props");
const itemType = useModelState("item_type");
const returnObject = useModelState("return_object");
const valueComparator = useModelState("value_comparator");
const menu = useModelState("menu");
const menuIcon = useModelState("menu_icon");
const menuProps = useModelState("menu_props");
const noDataText = useModelState("no_data_text");
const openOnClear = useModelState("open_on_clear");
const itemColor = useModelState("item_color");
const noAutoScroll = useModelState("no_auto_scroll");
const closeText = useModelState("close_text");
const openText = useModelState("open_text");
const counter = useModelState("counter");
const persistentPlaceholder = useModelState("persistent_placeholder");
const persistentCounter = useModelState("persistent_counter");
const suffix = useModelState("suffix");
const centerAffix = useModelState("center_affix");
const glow = useModelState("glow");
const iconColor = useModelState("icon_color");
const hideSpinButtons = useModelState("hide_spin_buttons");
const hint = useModelState("hint");
const persistentHint = useModelState("persistent_hint");
const messages = useModelState("messages");
const errorMessages = useModelState("error_messages");
const maxErrors = useModelState("max_errors");
const rules = useModelState("rules");
const validateOn = useModelState("validate_on");
const focused = useModelState("focused");
const hideDetails = useModelState("hide_details");
const appendInnerIcon = useModelState("append_inner_icon");
const clearable = useModelState("clearable");
const clearIcon = useModelState("clear_icon");
const persistentClear = useModelState("persistent_clear");
const prependInnerIcon = useModelState("prepend_inner_icon");
const singleLine = useModelState("single_line");
const counterValue = useModelState("counter_value");
const modelModifiers = useModelState("model_modifiers");
</script>