<template>
  <v-autocomplete
    :flat="_flat"
    :search="_search"
    :type="_type"
    :modelValue="_model_value"
    :error="_error"
    :reverse="_reverse"
    :density="_density"
    :maxWidth="_max_width"
    :minWidth="_min_width"
    :width="_width"
    :rounded="_rounded"
    :tile="_tile"
    :theme="_theme"
    :color="_color"
    :variant="_variant"
    :name="_name"
    :autocomplete="_autocomplete"
    :disabled="_disabled"
    :multiple="_multiple"
    :placeholder="_placeholder"
    :id="_id"
    :prefix="_prefix"
    :role="_role"
    :autofocus="_autofocus"
    :items="_items"
    :active="_active"
    :baseColor="_base_color"
    :prependIcon="_prepend_icon"
    :appendIcon="_append_icon"
    :readonly="_readonly"
    :loading="_loading"
    :label="_label"
    :autoSelectFirst="_auto_select_first"
    :clearOnSelect="_clear_on_select"
    :filterMode="_filter_mode"
    :noFilter="_no_filter"
    :customFilter="_custom_filter"
    :customKeyFilter="_custom_key_filter"
    :filterKeys="_filter_keys"
    :chips="_chips"
    :closableChips="_closable_chips"
    :eager="_eager"
    :hideNoData="_hide_no_data"
    :hideSelected="_hide_selected"
    :listProps="_list_props"
    :bgColor="_bg_color"
    :itemTitle="_item_title"
    :itemValue="_item_value"
    :itemChildren="_item_children"
    :itemProps="_item_props"
    :itemType="_item_type"
    :returnObject="_return_object"
    :valueComparator="_value_comparator"
    :menu="_menu"
    :menuIcon="_menu_icon"
    :menuProps="_menu_props"
    :noDataText="_no_data_text"
    :openOnClear="_open_on_clear"
    :itemColor="_item_color"
    :noAutoScroll="_no_auto_scroll"
    :closeText="_close_text"
    :openText="_open_text"
    :counter="_counter"
    :persistentPlaceholder="_persistent_placeholder"
    :persistentCounter="_persistent_counter"
    :suffix="_suffix"
    :centerAffix="_center_affix"
    :glow="_glow"
    :iconColor="_icon_color"
    :hideSpinButtons="_hide_spin_buttons"
    :hint="_hint"
    :persistentHint="_persistent_hint"
    :messages="_messages"
    :errorMessages="_error_messages"
    :maxErrors="_max_errors"
    :rules="_rules"
    :validateOn="_validate_on"
    :focused="_focused"
    :hideDetails="_hide_details"
    :appendInnerIcon="_append_inner_icon"
    :clearable="_clearable"
    :clearIcon="_clear_icon"
    :persistentClear="_persistent_clear"
    :prependInnerIcon="_prepend_inner_icon"
    :singleLine="_single_line"
    :counterValue="_counter_value"
    :modelModifiers="_model_modifiers"
  >
    {{ children }}
  </v-autocomplete>
</template>

<script setup>
import { useModelState } from "@pyvuetify/vuetify";

// Reactive state synced with Python
const children = useModelState("children");
const _flat = useModelState("flat");
const _search = useModelState("search");
const _type = useModelState("type");
const _model_value = useModelState("model_value");
const _error = useModelState("error");
const _reverse = useModelState("reverse");
const _density = useModelState("density");
const _max_width = useModelState("max_width");
const _min_width = useModelState("min_width");
const _width = useModelState("width");
const _rounded = useModelState("rounded");
const _tile = useModelState("tile");
const _theme = useModelState("theme");
const _color = useModelState("color");
const _variant = useModelState("variant");
const _name = useModelState("name");
const _autocomplete = useModelState("autocomplete");
const _disabled = useModelState("disabled");
const _multiple = useModelState("multiple");
const _placeholder = useModelState("placeholder");
const _id = useModelState("id");
const _prefix = useModelState("prefix");
const _role = useModelState("role");
const _autofocus = useModelState("autofocus");
const _items = useModelState("items");
const _active = useModelState("active");
const _base_color = useModelState("base_color");
const _prepend_icon = useModelState("prepend_icon");
const _append_icon = useModelState("append_icon");
const _readonly = useModelState("readonly");
const _loading = useModelState("loading");
const _label = useModelState("label");
const _auto_select_first = useModelState("auto_select_first");
const _clear_on_select = useModelState("clear_on_select");
const _filter_mode = useModelState("filter_mode");
const _no_filter = useModelState("no_filter");
const _custom_filter = useModelState("custom_filter");
const _custom_key_filter = useModelState("custom_key_filter");
const _filter_keys = useModelState("filter_keys");
const _chips = useModelState("chips");
const _closable_chips = useModelState("closable_chips");
const _eager = useModelState("eager");
const _hide_no_data = useModelState("hide_no_data");
const _hide_selected = useModelState("hide_selected");
const _list_props = useModelState("list_props");
const _bg_color = useModelState("bg_color");
const _item_title = useModelState("item_title");
const _item_value = useModelState("item_value");
const _item_children = useModelState("item_children");
const _item_props = useModelState("item_props");
const _item_type = useModelState("item_type");
const _return_object = useModelState("return_object");
const _value_comparator = useModelState("value_comparator");
const _menu = useModelState("menu");
const _menu_icon = useModelState("menu_icon");
const _menu_props = useModelState("menu_props");
const _no_data_text = useModelState("no_data_text");
const _open_on_clear = useModelState("open_on_clear");
const _item_color = useModelState("item_color");
const _no_auto_scroll = useModelState("no_auto_scroll");
const _close_text = useModelState("close_text");
const _open_text = useModelState("open_text");
const _counter = useModelState("counter");
const _persistent_placeholder = useModelState("persistent_placeholder");
const _persistent_counter = useModelState("persistent_counter");
const _suffix = useModelState("suffix");
const _center_affix = useModelState("center_affix");
const _glow = useModelState("glow");
const _icon_color = useModelState("icon_color");
const _hide_spin_buttons = useModelState("hide_spin_buttons");
const _hint = useModelState("hint");
const _persistent_hint = useModelState("persistent_hint");
const _messages = useModelState("messages");
const _error_messages = useModelState("error_messages");
const _max_errors = useModelState("max_errors");
const _rules = useModelState("rules");
const _validate_on = useModelState("validate_on");
const _focused = useModelState("focused");
const _hide_details = useModelState("hide_details");
const _append_inner_icon = useModelState("append_inner_icon");
const _clearable = useModelState("clearable");
const _clear_icon = useModelState("clear_icon");
const _persistent_clear = useModelState("persistent_clear");
const _prepend_inner_icon = useModelState("prepend_inner_icon");
const _single_line = useModelState("single_line");
const _counter_value = useModelState("counter_value");
const _model_modifiers = useModelState("model_modifiers");
</script>