<template>
  <v-color-input
    :flat="_flat"
    :tag="_tag"
    :type="_type"
    :reverse="_reverse"
    :name="_name"
    :mode="_mode"
    :error="_error"
    :label="_label"
    :title="_title"
    :autocomplete="_autocomplete"
    :disabled="_disabled"
    :placeholder="_placeholder"
    :width="_width"
    :id="_id"
    :prefix="_prefix"
    :role="_role"
    :autofocus="_autofocus"
    :modelValue="_model_value"
    :color="_color"
    :density="_density"
    :border="_border"
    :elevation="_elevation"
    :rounded="_rounded"
    :tile="_tile"
    :theme="_theme"
    :variant="_variant"
    :maxWidth="_max_width"
    :minWidth="_min_width"
    :bgColor="_bg_color"
    :position="_position"
    :baseColor="_base_color"
    :active="_active"
    :prependIcon="_prepend_icon"
    :appendIcon="_append_icon"
    :readonly="_readonly"
    :loading="_loading"
    :divided="_divided"
    :hideHeader="_hide_header"
    :messages="_messages"
    :centerAffix="_center_affix"
    :glow="_glow"
    :iconColor="_icon_color"
    :hideSpinButtons="_hide_spin_buttons"
    :hint="_hint"
    :persistentHint="_persistent_hint"
    :errorMessages="_error_messages"
    :maxErrors="_max_errors"
    :rules="_rules"
    :validateOn="_validate_on"
    :validationValue="_validation_value"
    :focused="_focused"
    :hideDetails="_hide_details"
    :counter="_counter"
    :hidePip="_hide_pip"
    :colorPip="_color_pip"
    :pipIcon="_pip_icon"
    :pipLocation="_pip_location"
    :pipVariant="_pip_variant"
    :canvasHeight="_canvas_height"
    :dotSize="_dot_size"
    :hideCanvas="_hide_canvas"
    :hideSliders="_hide_sliders"
    :hideInputs="_hide_inputs"
    :modes="_modes"
    :showSwatches="_show_swatches"
    :swatchesMaxHeight="_swatches_max_height"
    :landscape="_landscape"
    :hideTitle="_hide_title"
    :hideEyeDropper="_hide_eye_dropper"
    :eyeDropperIcon="_eye_dropper_icon"
    :swatches="_swatches"
    :cancelText="_cancel_text"
    :okText="_ok_text"
    :hideActions="_hide_actions"
    :persistentPlaceholder="_persistent_placeholder"
    :persistentCounter="_persistent_counter"
    :suffix="_suffix"
    :appendInnerIcon="_append_inner_icon"
    :clearable="_clearable"
    :clearIcon="_clear_icon"
    :dirty="_dirty"
    :persistentClear="_persistent_clear"
    :prependInnerIcon="_prepend_inner_icon"
    :singleLine="_single_line"
    :counterValue="_counter_value"
    :modelModifiers="_model_modifiers"
    :pickerProps="_picker_props"
  >
    {{ children }}
  </v-color-input>
</template>

<script setup>
import { useModelState } from "@pyvuetify/vuetify";

// Reactive state synced with Python
const children = useModelState("children");
const _flat = useModelState("flat");
const _tag = useModelState("tag");
const _type = useModelState("type");
const _reverse = useModelState("reverse");
const _name = useModelState("name");
const _mode = useModelState("mode");
const _error = useModelState("error");
const _label = useModelState("label");
const _title = useModelState("title");
const _autocomplete = useModelState("autocomplete");
const _disabled = useModelState("disabled");
const _placeholder = useModelState("placeholder");
const _width = useModelState("width");
const _id = useModelState("id");
const _prefix = useModelState("prefix");
const _role = useModelState("role");
const _autofocus = useModelState("autofocus");
const _model_value = useModelState("model_value");
const _color = useModelState("color");
const _density = useModelState("density");
const _border = useModelState("border");
const _elevation = useModelState("elevation");
const _rounded = useModelState("rounded");
const _tile = useModelState("tile");
const _theme = useModelState("theme");
const _variant = useModelState("variant");
const _max_width = useModelState("max_width");
const _min_width = useModelState("min_width");
const _bg_color = useModelState("bg_color");
const _position = useModelState("position");
const _base_color = useModelState("base_color");
const _active = useModelState("active");
const _prepend_icon = useModelState("prepend_icon");
const _append_icon = useModelState("append_icon");
const _readonly = useModelState("readonly");
const _loading = useModelState("loading");
const _divided = useModelState("divided");
const _hide_header = useModelState("hide_header");
const _messages = useModelState("messages");
const _center_affix = useModelState("center_affix");
const _glow = useModelState("glow");
const _icon_color = useModelState("icon_color");
const _hide_spin_buttons = useModelState("hide_spin_buttons");
const _hint = useModelState("hint");
const _persistent_hint = useModelState("persistent_hint");
const _error_messages = useModelState("error_messages");
const _max_errors = useModelState("max_errors");
const _rules = useModelState("rules");
const _validate_on = useModelState("validate_on");
const _validation_value = useModelState("validation_value");
const _focused = useModelState("focused");
const _hide_details = useModelState("hide_details");
const _counter = useModelState("counter");
const _hide_pip = useModelState("hide_pip");
const _color_pip = useModelState("color_pip");
const _pip_icon = useModelState("pip_icon");
const _pip_location = useModelState("pip_location");
const _pip_variant = useModelState("pip_variant");
const _canvas_height = useModelState("canvas_height");
const _dot_size = useModelState("dot_size");
const _hide_canvas = useModelState("hide_canvas");
const _hide_sliders = useModelState("hide_sliders");
const _hide_inputs = useModelState("hide_inputs");
const _modes = useModelState("modes");
const _show_swatches = useModelState("show_swatches");
const _swatches_max_height = useModelState("swatches_max_height");
const _landscape = useModelState("landscape");
const _hide_title = useModelState("hide_title");
const _hide_eye_dropper = useModelState("hide_eye_dropper");
const _eye_dropper_icon = useModelState("eye_dropper_icon");
const _swatches = useModelState("swatches");
const _cancel_text = useModelState("cancel_text");
const _ok_text = useModelState("ok_text");
const _hide_actions = useModelState("hide_actions");
const _persistent_placeholder = useModelState("persistent_placeholder");
const _persistent_counter = useModelState("persistent_counter");
const _suffix = useModelState("suffix");
const _append_inner_icon = useModelState("append_inner_icon");
const _clearable = useModelState("clearable");
const _clear_icon = useModelState("clear_icon");
const _dirty = useModelState("dirty");
const _persistent_clear = useModelState("persistent_clear");
const _prepend_inner_icon = useModelState("prepend_inner_icon");
const _single_line = useModelState("single_line");
const _counter_value = useModelState("counter_value");
const _model_modifiers = useModelState("model_modifiers");
const _picker_props = useModelState("picker_props");
</script>