<template>
  <v-date-input
    :flat="_flat"
    :tag="_tag"
    :type="_type"
    :reverse="_reverse"
    :name="_name"
    :error="_error"
    :header="_header"
    :label="_label"
    :menu="_menu"
    :title="_title"
    :autocomplete="_autocomplete"
    :disabled="_disabled"
    :max="_max"
    :min="_min"
    :multiple="_multiple"
    :placeholder="_placeholder"
    :width="_width"
    :id="_id"
    :prefix="_prefix"
    :role="_role"
    :autofocus="_autofocus"
    :modelValue="_model_value"
    :location="_location"
    :color="_color"
    :density="_density"
    :border="_border"
    :elevation="_elevation"
    :rounded="_rounded"
    :tile="_tile"
    :theme="_theme"
    :text="_text"
    :variant="_variant"
    :transition="_transition"
    :maxWidth="_max_width"
    :minWidth="_min_width"
    :bgColor="_bg_color"
    :mobile="_mobile"
    :mobileBreakpoint="_mobile_breakpoint"
    :position="_position"
    :baseColor="_base_color"
    :active="_active"
    :prependIcon="_prepend_icon"
    :appendIcon="_append_icon"
    :readonly="_readonly"
    :loading="_loading"
    :divided="_divided"
    :weekdays="_weekdays"
    :firstDayOfWeek="_first_day_of_week"
    :firstDayOfYear="_first_day_of_year"
    :weekdayFormat="_weekday_format"
    :month="_month"
    :events="_events"
    :eventColor="_event_color"
    :year="_year"
    :showWeek="_show_week"
    :hideHeader="_hide_header"
    :messages="_messages"
    :nextIcon="_next_icon"
    :prevIcon="_prev_icon"
    :reverseTransition="_reverse_transition"
    :centerAffix="_center_affix"
    :glow="_glow"
    :iconColor="_icon_color"
    :hideSpinButtons="_hide_spin_buttons"
    :hint="_hint"
    :persistentHint="_persistent_hint"
    :errorMessages="_error_messages"
    :maxErrors="_max_errors"
    :rules="_rules"
    :validateOn="_validate_on"
    :validationValue="_validation_value"
    :focused="_focused"
    :hideDetails="_hide_details"
    :counter="_counter"
    :landscape="_landscape"
    :hideTitle="_hide_title"
    :cancelText="_cancel_text"
    :okText="_ok_text"
    :hideActions="_hide_actions"
    :persistentPlaceholder="_persistent_placeholder"
    :persistentCounter="_persistent_counter"
    :suffix="_suffix"
    :appendInnerIcon="_append_inner_icon"
    :clearable="_clearable"
    :clearIcon="_clear_icon"
    :dirty="_dirty"
    :persistentClear="_persistent_clear"
    :prependInnerIcon="_prepend_inner_icon"
    :singleLine="_single_line"
    :counterValue="_counter_value"
    :modelModifiers="_model_modifiers"
    :pickerProps="_picker_props"
    :displayFormat="_display_format"
    :updateOn="_update_on"
    :headerColor="_header_color"
    :headerDateFormat="_header_date_format"
    :landscapeHeaderWidth="_landscape_header_width"
    :controlHeight="_control_height"
    :controlVariant="_control_variant"
    :noMonthPicker="_no_month_picker"
    :modeIcon="_mode_icon"
    :viewMode="_view_mode"
    :hideWeekdays="_hide_weekdays"
    :showAdjacentMonths="_show_adjacent_months"
    :weeksInMonth="_weeks_in_month"
    :allowedDates="_allowed_dates"
    :allowedMonths="_allowed_months"
    :allowedYears="_allowed_years"
    :inputFormat="_input_format"
  >
    {{ children }}
  </v-date-input>
</template>

<script setup>
import { useModelState } from "@pyvuetify/vuetify";

// Reactive state synced with Python
const children = useModelState("children");
const _flat = useModelState("flat");
const _tag = useModelState("tag");
const _type = useModelState("type");
const _reverse = useModelState("reverse");
const _name = useModelState("name");
const _error = useModelState("error");
const _header = useModelState("header");
const _label = useModelState("label");
const _menu = useModelState("menu");
const _title = useModelState("title");
const _autocomplete = useModelState("autocomplete");
const _disabled = useModelState("disabled");
const _max = useModelState("max");
const _min = useModelState("min");
const _multiple = useModelState("multiple");
const _placeholder = useModelState("placeholder");
const _width = useModelState("width");
const _id = useModelState("id");
const _prefix = useModelState("prefix");
const _role = useModelState("role");
const _autofocus = useModelState("autofocus");
const _model_value = useModelState("model_value");
const _location = useModelState("location");
const _color = useModelState("color");
const _density = useModelState("density");
const _border = useModelState("border");
const _elevation = useModelState("elevation");
const _rounded = useModelState("rounded");
const _tile = useModelState("tile");
const _theme = useModelState("theme");
const _text = useModelState("text");
const _variant = useModelState("variant");
const _transition = useModelState("transition");
const _max_width = useModelState("max_width");
const _min_width = useModelState("min_width");
const _bg_color = useModelState("bg_color");
const _mobile = useModelState("mobile");
const _mobile_breakpoint = useModelState("mobile_breakpoint");
const _position = useModelState("position");
const _base_color = useModelState("base_color");
const _active = useModelState("active");
const _prepend_icon = useModelState("prepend_icon");
const _append_icon = useModelState("append_icon");
const _readonly = useModelState("readonly");
const _loading = useModelState("loading");
const _divided = useModelState("divided");
const _weekdays = useModelState("weekdays");
const _first_day_of_week = useModelState("first_day_of_week");
const _first_day_of_year = useModelState("first_day_of_year");
const _weekday_format = useModelState("weekday_format");
const _month = useModelState("month");
const _events = useModelState("events");
const _event_color = useModelState("event_color");
const _year = useModelState("year");
const _show_week = useModelState("show_week");
const _hide_header = useModelState("hide_header");
const _messages = useModelState("messages");
const _next_icon = useModelState("next_icon");
const _prev_icon = useModelState("prev_icon");
const _reverse_transition = useModelState("reverse_transition");
const _center_affix = useModelState("center_affix");
const _glow = useModelState("glow");
const _icon_color = useModelState("icon_color");
const _hide_spin_buttons = useModelState("hide_spin_buttons");
const _hint = useModelState("hint");
const _persistent_hint = useModelState("persistent_hint");
const _error_messages = useModelState("error_messages");
const _max_errors = useModelState("max_errors");
const _rules = useModelState("rules");
const _validate_on = useModelState("validate_on");
const _validation_value = useModelState("validation_value");
const _focused = useModelState("focused");
const _hide_details = useModelState("hide_details");
const _counter = useModelState("counter");
const _landscape = useModelState("landscape");
const _hide_title = useModelState("hide_title");
const _cancel_text = useModelState("cancel_text");
const _ok_text = useModelState("ok_text");
const _hide_actions = useModelState("hide_actions");
const _persistent_placeholder = useModelState("persistent_placeholder");
const _persistent_counter = useModelState("persistent_counter");
const _suffix = useModelState("suffix");
const _append_inner_icon = useModelState("append_inner_icon");
const _clearable = useModelState("clearable");
const _clear_icon = useModelState("clear_icon");
const _dirty = useModelState("dirty");
const _persistent_clear = useModelState("persistent_clear");
const _prepend_inner_icon = useModelState("prepend_inner_icon");
const _single_line = useModelState("single_line");
const _counter_value = useModelState("counter_value");
const _model_modifiers = useModelState("model_modifiers");
const _picker_props = useModelState("picker_props");
const _display_format = useModelState("display_format");
const _update_on = useModelState("update_on");
const _header_color = useModelState("header_color");
const _header_date_format = useModelState("header_date_format");
const _landscape_header_width = useModelState("landscape_header_width");
const _control_height = useModelState("control_height");
const _control_variant = useModelState("control_variant");
const _no_month_picker = useModelState("no_month_picker");
const _mode_icon = useModelState("mode_icon");
const _view_mode = useModelState("view_mode");
const _hide_weekdays = useModelState("hide_weekdays");
const _show_adjacent_months = useModelState("show_adjacent_months");
const _weeks_in_month = useModelState("weeks_in_month");
const _allowed_dates = useModelState("allowed_dates");
const _allowed_months = useModelState("allowed_months");
const _allowed_years = useModelState("allowed_years");
const _input_format = useModelState("input_format");
</script>