<template>
  <v-treeview
    :search="_search"
    :border="_border"
    :modelValue="_model_value"
    :density="_density"
    :height="_height"
    :maxHeight="_max_height"
    :maxWidth="_max_width"
    :minHeight="_min_height"
    :minWidth="_min_width"
    :width="_width"
    :elevation="_elevation"
    :rounded="_rounded"
    :tile="_tile"
    :tag="_tag"
    :theme="_theme"
    :color="_color"
    :variant="_variant"
    :activated="_activated"
    :disabled="_disabled"
    :items="_items"
    :activeColor="_active_color"
    :baseColor="_base_color"
    :slim="_slim"
    :filterMode="_filter_mode"
    :noFilter="_no_filter"
    :customFilter="_custom_filter"
    :customKeyFilter="_custom_key_filter"
    :filterKeys="_filter_keys"
    :hideNoData="_hide_no_data"
    :activeClass="_active_class"
    :bgColor="_bg_color"
    :filterable="_filterable"
    :expandIcon="_expand_icon"
    :collapseIcon="_collapse_icon"
    :lines="_lines"
    :prependGap="_prepend_gap"
    :indent="_indent"
    :activatable="_activatable"
    :selectable="_selectable"
    :opened="_opened"
    :selected="_selected"
    :mandatory="_mandatory"
    :itemsRegistration="_items_registration"
    :activeStrategy="_active_strategy"
    :selectStrategy="_select_strategy"
    :itemTitle="_item_title"
    :itemValue="_item_value"
    :itemChildren="_item_children"
    :itemProps="_item_props"
    :itemType="_item_type"
    :returnObject="_return_object"
    :valueComparator="_value_comparator"
    :openOnClick="_open_on_click"
    :noDataText="_no_data_text"
    :hideActions="_hide_actions"
    :falseIcon="_false_icon"
    :trueIcon="_true_icon"
    :openAll="_open_all"
    :fluid="_fluid"
    :loadingIcon="_loading_icon"
    :indeterminateIcon="_indeterminate_icon"
    :selectedColor="_selected_color"
    :separateRoots="_separate_roots"
    :indentLines="_indent_lines"
    :loadChildren="_load_children"
  >
    {{ children }}
  </v-treeview>
</template>

<script setup>
import { useModelState } from "@pyvuetify/vuetify";

// Reactive state synced with Python
const children = useModelState("children");
const _search = useModelState("search");
const _border = useModelState("border");
const _model_value = useModelState("model_value");
const _density = useModelState("density");
const _height = useModelState("height");
const _max_height = useModelState("max_height");
const _max_width = useModelState("max_width");
const _min_height = useModelState("min_height");
const _min_width = useModelState("min_width");
const _width = useModelState("width");
const _elevation = useModelState("elevation");
const _rounded = useModelState("rounded");
const _tile = useModelState("tile");
const _tag = useModelState("tag");
const _theme = useModelState("theme");
const _color = useModelState("color");
const _variant = useModelState("variant");
const _activated = useModelState("activated");
const _disabled = useModelState("disabled");
const _items = useModelState("items");
const _active_color = useModelState("active_color");
const _base_color = useModelState("base_color");
const _slim = useModelState("slim");
const _filter_mode = useModelState("filter_mode");
const _no_filter = useModelState("no_filter");
const _custom_filter = useModelState("custom_filter");
const _custom_key_filter = useModelState("custom_key_filter");
const _filter_keys = useModelState("filter_keys");
const _hide_no_data = useModelState("hide_no_data");
const _active_class = useModelState("active_class");
const _bg_color = useModelState("bg_color");
const _filterable = useModelState("filterable");
const _expand_icon = useModelState("expand_icon");
const _collapse_icon = useModelState("collapse_icon");
const _lines = useModelState("lines");
const _prepend_gap = useModelState("prepend_gap");
const _indent = useModelState("indent");
const _activatable = useModelState("activatable");
const _selectable = useModelState("selectable");
const _opened = useModelState("opened");
const _selected = useModelState("selected");
const _mandatory = useModelState("mandatory");
const _items_registration = useModelState("items_registration");
const _active_strategy = useModelState("active_strategy");
const _select_strategy = useModelState("select_strategy");
const _item_title = useModelState("item_title");
const _item_value = useModelState("item_value");
const _item_children = useModelState("item_children");
const _item_props = useModelState("item_props");
const _item_type = useModelState("item_type");
const _return_object = useModelState("return_object");
const _value_comparator = useModelState("value_comparator");
const _open_on_click = useModelState("open_on_click");
const _no_data_text = useModelState("no_data_text");
const _hide_actions = useModelState("hide_actions");
const _false_icon = useModelState("false_icon");
const _true_icon = useModelState("true_icon");
const _open_all = useModelState("open_all");
const _fluid = useModelState("fluid");
const _loading_icon = useModelState("loading_icon");
const _indeterminate_icon = useModelState("indeterminate_icon");
const _selected_color = useModelState("selected_color");
const _separate_roots = useModelState("separate_roots");
const _indent_lines = useModelState("indent_lines");
const _load_children = useModelState("load_children");
</script>