import pyvuetify as v

v.Toolbar(
    color="blue-grey-darken-3",
    children=[
        v.Spacer(),
        v.Btn(
            class_="text-none",
            stacked=True,
            children=[
                v.Badge(
                    color="success",
                    dot=True,
                    children=[
                        v.Icon(children=["mdi-home-outline"]),
                    ],
                ),
            ],
        ),
        v.Btn(
            class_="text-none",
            stacked=True,
            children=[
                v.Icon(children=["mdi-account-multiple-outline"]),
            ],
        ),
        v.Btn(
            class_="text-none",
            stacked=True,
            children=[
                v.Badge(
                    color="error",
                    content="9+",
                    children=[
                        v.Icon(children=["mdi-store-outline"]),
                    ],
                ),
            ],
        ),
        v.Btn(
            class_="text-none",
            stacked=True,
            children=[
                v.Badge(
                    color="error",
                    content="2",
                    children=[
                        v.Icon(children=["mdi-bell-outline"]),
                    ],
                ),
            ],
        ),
        v.Btn(
            class_="text-none",
            stacked=True,
            children=[
                v.Icon(children=["mdi-menu"]),
            ],
        ),
        v.Spacer(),
    ],
)
