import ipyvuetify as v

v.Card(
    class_="mx-auto my-2",
    max_width=400,
    children=[
        v.Card(
            dark=True,
            flat=True,
            children=[
                v.Btn(
                    absolute=True,
                    bottom=True,
                    color="pink",
                    right=True,
                    fab=True,
                    children=[v.Icon(children=["mdi-plus"])],
                ),
                v.CardTitle(
                    class_="pa-2 purple lighten-3",
                    children=[
                        v.Btn(
                            icon=True,
                            children=[v.Icon(children=["mdi-menu"])],
                        ),
                        v.Html(
                            tag="h3",
                            class_="text-h6 font-weight-light text-center grow",
                            children=["Timeline"],
                        ),
                        v.Avatar(
                            children=[
                                v.Img(
                                    src="https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraight&accessoriesType=Blank&hairColor=BrownDark&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light"
                                )
                            ]
                        ),
                    ],
                ),
                v.Img(
                    src="https://cdn.vuetifyjs.com/images/cards/forest.jpg",
                    gradient="to top, rgba(0,0,0,.44), rgba(0,0,0,.44)",
                    children=[
                        v.Container(
                            class_="fill-height",
                            children=[
                                v.Row(
                                    align="center",
                                    children=[
                                        v.Html(
                                            tag="strong",
                                            class_="text-h1 font-weight-regular mr-6",
                                            children=["8"],
                                        ),
                                        v.Row(
                                            justify="end",
                                            children=[
                                                v.Html(
                                                    tag="div",
                                                    class_="text-h5 font-weight-light",
                                                    children=["Monday"],
                                                ),
                                                v.Html(
                                                    tag="div",
                                                    class_="text-uppercase font-weight-light",
                                                    children=["February 2015"],
                                                ),
                                            ],
                                        ),
                                    ],
                                )
                            ],
                        )
                    ],
                ),
            ],
        ),
        v.CardText(
            class_="py-0",
            children=[
                v.Timeline(
                    align_top=True,
                    dense=True,
                    children=[
                        v.TimelineItem(
                            color="pink",
                            small=True,
                            children=[
                                v.Row(
                                    class_="pt-1",
                                    children=[
                                        v.Col(
                                            cols=3,
                                            children=[
                                                v.Html(
                                                    tag="strong",
                                                    children=["5pm"],
                                                )
                                            ],
                                        ),
                                        v.Col(
                                            children=[
                                                v.Html(
                                                    tag="strong",
                                                    children=["New Icon"],
                                                ),
                                                v.Html(
                                                    tag="div",
                                                    class_="text-caption",
                                                    children=["Mobile App"],
                                                ),
                                            ],
                                        ),
                                    ],
                                )
                            ],
                        ),
                        v.TimelineItem(
                            color="teal lighten-3",
                            small=True,
                            children=[
                                v.Row(
                                    class_="pt-1",
                                    children=[
                                        v.Col(
                                            cols=3,
                                            children=[
                                                v.Html(
                                                    tag="strong",
                                                    children=["3-4pm"],
                                                )
                                            ],
                                        ),
                                        v.Col(
                                            children=[
                                                v.Html(
                                                    tag="strong",
                                                    children=["Design Stand Up"],
                                                ),
                                                v.Html(
                                                    tag="div",
                                                    class_="text-caption mb-2",
                                                    children=["Hangouts"],
                                                ),
                                                v.Avatar(
                                                    children=[
                                                        v.Img(
                                                            src="https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Kurt&hairColor=Red&facialHairType=BeardLight&facialHairColor=BrownDark&clotheType=GraphicShirt&clotheColor=Gray01&graphicType=Skull&eyeType=Wink&eyebrowType=RaisedExcitedNatural&mouthType=Disbelief&skinColor=Brown"
                                                        )
                                                    ]
                                                ),
                                                v.Avatar(
                                                    children=[
                                                        v.Img(
                                                            src="https://avataaars.io/?avatarStyle=Circle&topType=ShortHairFrizzle&accessoriesType=Prescription02&hairColor=Black&facialHairType=MoustacheMagnum&facialHairColor=BrownDark&clotheType=BlazerSweater&clotheColor=Black&eyeType=Default&eyebrowType=FlatNatural&mouthType=Default&skinColor=Tanned"
                                                        )
                                                    ]
                                                ),
                                                v.Avatar(
                                                    children=[
                                                        v.Img(
                                                            src="https://avataaars.io/?avatarStyle=Circle&topType=LongHairMiaWallace&accessoriesType=Sunglasses&hairColor=BlondeGolden&facialHairType=Blank&clotheType=BlazerSweater&eyeType=Surprised&eyebrowType=RaisedExcited&mouthType=Smile&skinColor=Pale"
                                                        )
                                                    ]
                                                ),
                                            ],
                                        ),
                                    ],
                                )
                            ],
                        ),
                        v.TimelineItem(
                            color="pink",
                            small=True,
                            children=[
                                v.Row(
                                    class_="pt-1",
                                    children=[
                                        v.Col(
                                            cols=3,
                                            children=[
                                                v.Html(
                                                    tag="strong",
                                                    children=["12pm"],
                                                )
                                            ],
                                        ),
                                        v.Col(
                                            children=[
                                                v.Html(
                                                    tag="strong",
                                                    children=["Lunch break"],
                                                )
                                            ],
                                        ),
                                    ],
                                )
                            ],
                        ),
                        v.TimelineItem(
                            color="teal lighten-3",
                            small=True,
                            children=[
                                v.Row(
                                    class_="pt-1",
                                    children=[
                                        v.Col(
                                            cols=3,
                                            children=[
                                                v.Html(
                                                    tag="strong",
                                                    children=["9-11am"],
                                                )
                                            ],
                                        ),
                                        v.Col(
                                            children=[
                                                v.Html(
                                                    tag="strong",
                                                    children=["Finish Home Screen"],
                                                ),
                                                v.Html(
                                                    tag="div",
                                                    class_="text-caption",
                                                    children=["Web App"],
                                                ),
                                            ],
                                        ),
                                    ],
                                )
                            ],
                        ),
                    ],
                )
            ],
        ),
    ],
)
