import pyvuetify as v

v.Timeline(
    align="start",
    side="end",
    children=[
        v.TimelineItem(
            dot_color="pink",
            size="small",
            children=[
                v.Html(
                    tag="div",
                    class_="d-flex",
                    children=[
                        v.Html(
                            tag="strong",
                            class_="me-4",
                            children=["5pm"],
                        ),
                        v.Html(
                            tag="div",
                            children=[
                                v.Html(
                                    tag="strong",
                                    children=["New Icon"],
                                ),
                                v.Html(
                                    tag="div",
                                    class_="text-body-small",
                                    children=["Mobile App"],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
        v.TimelineItem(
            dot_color="teal-lighten-3",
            size="small",
            children=[
                v.Html(
                    tag="div",
                    class_="d-flex",
                    children=[
                        v.Html(
                            tag="strong",
                            class_="me-4",
                            children=["3-4pm"],
                        ),
                        v.Html(
                            tag="div",
                            children=[
                                v.Html(
                                    tag="strong",
                                    children=["Design Stand Up"],
                                ),
                                v.Html(
                                    tag="div",
                                    class_="text-body-small mb-2",
                                    children=["Hangouts"],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
        v.TimelineItem(
            dot_color="pink",
            size="small",
            children=[
                v.Html(
                    tag="div",
                    class_="d-flex",
                    children=[
                        v.Html(
                            tag="strong",
                            class_="me-4",
                            children=["12pm"],
                        ),
                        v.Html(
                            tag="div",
                            children=[
                                v.Html(
                                    tag="strong",
                                    children=["Lunch break"],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
        v.TimelineItem(
            dot_color="teal-lighten-3",
            size="small",
            children=[
                v.Html(
                    tag="div",
                    class_="d-flex",
                    children=[
                        v.Html(
                            tag="strong",
                            class_="me-4",
                            children=["9-11am"],
                        ),
                        v.Html(
                            tag="div",
                            children=[
                                v.Html(
                                    tag="strong",
                                    children=["Finish Home Screen"],
                                ),
                                v.Html(
                                    tag="div",
                                    class_="text-body-small",
                                    children=["Web App"],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
