import pyvuetify as v

v.Html(
    tag="div",
    children=[
        v.ProgressLinear(
            buffer_value="0",
            color="red-lighten-2",
            stream=True,
        ),
        v.ProgressLinear(
            buffer_value="0",
            color="teal",
            model_value="20",
            stream=True,
        ),
        v.ProgressLinear(
            buffer_value="50",
            color="cyan",
            stream=True,
        ),
        v.ProgressLinear(
            buffer_value="60",
            color="orange",
            model_value="40",
            stream=True,
        ),
    ],
)
