import pyvuetify as v

v.Html(
    tag="div",
    children=[
        v.ProgressLinear(
            color="light-blue",
            height="10",
            model_value="10",
            striped=True,
        ),
        v.ProgressLinear(
            color="light-green-darken-4",
            height="10",
            model_value="20",
            striped=True,
        ),
        v.ProgressLinear(
            color="lime",
            height="10",
            model_value="45",
            striped=True,
        ),
        v.ProgressLinear(
            color="deep-orange",
            height="10",
            model_value="60",
            striped=True,
        ),
    ],
)
