import ipyvuetify as v

v.Container(
    children=[
        v.Form(
            children=[
                v.Row(
                    children=[
                        v.Col(
                            cols="12",
                            sm="6",
                            md="3",
                            children=[
                                v.TextField(
                                    label="Regular",
                                )
                            ],
                        ),
                        v.Col(
                            cols="12",
                            sm="6",
                            md="3",
                            children=[
                                v.TextField(
                                    label="Regular",
                                    placeholder="Placeholder",
                                )
                            ],
                        ),
                        v.Col(
                            cols="12",
                            sm="6",
                            md="3",
                            children=[
                                v.TextField(
                                    label="Solo",
                                    solo=True,
                                )
                            ],
                        ),
                        v.Col(
                            cols="12",
                            sm="6",
                            md="3",
                            children=[
                                v.TextField(
                                    label="Solo",
                                    placeholder="Placeholder",
                                    solo=True,
                                )
                            ],
                        ),
                        v.Col(
                            cols="12",
                            sm="6",
                            md="3",
                            children=[
                                v.TextField(
                                    label="Filled",
                                    filled=True,
                                )
                            ],
                        ),
                        v.Col(
                            cols="12",
                            sm="6",
                            md="3",
                            children=[
                                v.TextField(
                                    label="Filled",
                                    placeholder="Placeholder",
                                    filled=True,
                                )
                            ],
                        ),
                        v.Col(
                            cols="12",
                            sm="6",
                            md="3",
                            children=[
                                v.TextField(
                                    label="Outlined",
                                    outlined=True,
                                )
                            ],
                        ),
                        v.Col(
                            cols="12",
                            sm="6",
                            md="3",
                            children=[
                                v.TextField(
                                    label="Outlined",
                                    placeholder="Placeholder",
                                    outlined=True,
                                )
                            ],
                        ),
                    ]
                )
            ]
        )
    ]
)
