import pyvuetify as v

v.Form(
    children=[
        v.Container(
            children=[
                v.Row(
                    children=[
                        v.Col(
                            cols="12",
                            md="4",
                            sm="6",
                            children=[
                                v.TextField(
                                    label="Regular",
                                    placeholder="Placeholder",
                                ),
                            ],
                        ),
                        v.Col(
                            cols="12",
                            md="4",
                            sm="6",
                            children=[
                                v.TextField(
                                    label="Solo",
                                    placeholder="Placeholder",
                                    variant="solo",
                                ),
                            ],
                        ),
                        v.Col(
                            cols="12",
                            md="4",
                            sm="6",
                            children=[
                                v.TextField(
                                    label="Filled",
                                    placeholder="Placeholder",
                                    variant="filled",
                                ),
                            ],
                        ),
                        v.Col(
                            cols="12",
                            md="4",
                            sm="6",
                            children=[
                                v.TextField(
                                    label="Outlined",
                                    placeholder="Placeholder",
                                    variant="outlined",
                                ),
                            ],
                        ),
                        v.Col(
                            cols="12",
                            md="4",
                            sm="6",
                            children=[
                                v.TextField(
                                    label="Plain",
                                    placeholder="Placeholder",
                                    variant="plain",
                                ),
                            ],
                        ),
                        v.Col(
                            cols="12",
                            md="4",
                            sm="6",
                            children=[
                                v.TextField(
                                    label="Underlined",
                                    placeholder="Placeholder",
                                    variant="underlined",
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
