import pyvuetify as v

v.Html(
    tag="div",
    children=[
        v.Container(
            fluid=True,
            children=[
                v.Row(
                    children=[
                        v.Col(
                            cols="12",
                            md="4",
                            sm="4",
                            children=[
                                v.Checkbox(
                                    v_model="ex4",
                                    color="red",
                                    label="red",
                                    value="red",
                                    hide_details=True,
                                ),
                                v.Checkbox(
                                    v_model="ex4",
                                    color="red-darken-3",
                                    label="red-darken-3",
                                    value="red-darken-3",
                                    hide_details=True,
                                ),
                            ],
                        ),
                        v.Col(
                            cols="12",
                            md="4",
                            sm="4",
                            children=[
                                v.Checkbox(
                                    v_model="ex4",
                                    color="indigo",
                                    label="indigo",
                                    value="indigo",
                                    hide_details=True,
                                ),
                                v.Checkbox(
                                    v_model="ex4",
                                    color="indigo-darken-3",
                                    label="indigo-darken-3",
                                    value="indigo-darken-3",
                                    hide_details=True,
                                ),
                            ],
                        ),
                        v.Col(
                            cols="12",
                            md="4",
                            sm="4",
                            children=[
                                v.Checkbox(
                                    v_model="ex4",
                                    color="orange",
                                    label="orange",
                                    value="orange",
                                    hide_details=True,
                                ),
                                v.Checkbox(
                                    v_model="ex4",
                                    color="orange-darken-3",
                                    label="orange-darken-3",
                                    value="orange-darken-3",
                                    hide_details=True,
                                ),
                            ],
                        ),
                    ],
                ),
                v.Row(
                    class_="mt-12",
                    children=[
                        v.Col(
                            cols="12",
                            md="4",
                            sm="4",
                            children=[
                                v.Checkbox(
                                    v_model="ex4",
                                    color="primary",
                                    label="primary",
                                    value="primary",
                                    hide_details=True,
                                ),
                                v.Checkbox(
                                    v_model="ex4",
                                    color="secondary",
                                    label="secondary",
                                    value="secondary",
                                    hide_details=True,
                                ),
                            ],
                        ),
                        v.Col(
                            cols="12",
                            md="4",
                            sm="4",
                            children=[
                                v.Checkbox(
                                    v_model="ex4",
                                    color="success",
                                    label="success",
                                    value="success",
                                    hide_details=True,
                                ),
                                v.Checkbox(
                                    v_model="ex4",
                                    color="info",
                                    label="info",
                                    value="info",
                                    hide_details=True,
                                ),
                            ],
                        ),
                        v.Col(
                            cols="12",
                            md="4",
                            sm="4",
                            children=[
                                v.Checkbox(
                                    v_model="ex4",
                                    color="warning",
                                    label="warning",
                                    value="warning",
                                    hide_details=True,
                                ),
                                v.Checkbox(
                                    v_model="ex4",
                                    color="error",
                                    label="error",
                                    value="error",
                                    hide_details=True,
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
