import pyvuetify as v

v.Container(
    fluid=True,
    children=[
        v.Row(
            children=[
                v.Col(
                    cols="4",
                    children=["on"],
                ),
                v.Col(
                    cols="4",
                    children=["off"],
                ),
                v.Col(
                    cols="4",
                    children=["indeterminate"],
                ),
            ],
        ),
        v.Row(
            children=[
                v.Col(
                    cols="4",
                    children=[
                        v.Checkbox(model_value=True),
                    ],
                ),
                v.Col(
                    cols="4",
                    children=[
                        v.Checkbox(model_value=False),
                    ],
                ),
                v.Col(
                    cols="4",
                    children=[
                        v.Checkbox(indeterminate=True),
                    ],
                ),
            ],
        ),
        v.Row(
            children=[
                v.Col(
                    cols="4",
                    children=["on disabled"],
                ),
                v.Col(
                    cols="4",
                    children=["off disabled"],
                ),
            ],
        ),
        v.Row(
            children=[
                v.Col(
                    cols="4",
                    children=[
                        v.Checkbox(
                            model_value=True,
                            disabled=True,
                        ),
                    ],
                ),
                v.Col(
                    cols="4",
                    children=[
                        v.Checkbox(
                            model_value=False,
                            disabled=True,
                        ),
                    ],
                ),
                v.Col(
                    cols="4",
                    children=[
                        v.Checkbox(
                            disabled=True,
                            indeterminate=True,
                        ),
                    ],
                ),
            ],
        ),
    ],
)
