import pyvuetify as v

v.Html(
    tag="div",
    class_="text-center",
    children=[
        v.Container(
            children=[
                v.Row(
                    class_="justify-center",
                    children=[
                        v.Col(
                            cols="8",
                            children=[
                                v.Container(
                                    class_="max-width",
                                    children=[
                                        v.Pagination(
                                            v_model="page",
                                            length=15,
                                            class_="my-4",
                                        ),
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
