import pyvuetify as v

v.Card(
    class_="overflow-hidden mx-auto",
    height="200",
    max_width="500",
    children=[
        v.BottomNavigation(
            scroll_target="#hide-on-scroll-example",
            absolute=True,
            hide_on_scroll=True,
            horizontal=True,
            children=[
                v.Btn(
                    color="deep-purple-accent-4",
                    variant="text",
                    children=[
                        v.Html(
                            tag="span",
                            children=["Recents"],
                        ),
                        v.Icon(children=["mdi-history"]),
                    ],
                ),
                v.Btn(
                    color="deep-purple-accent-4",
                    variant="text",
                    children=[
                        v.Html(
                            tag="span",
                            children=["Favorites"],
                        ),
                        v.Icon(children=["mdi-heart"]),
                    ],
                ),
                v.Btn(
                    color="deep-purple-accent-4",
                    variant="text",
                    children=[
                        v.Html(
                            tag="span",
                            children=["Nearby"],
                        ),
                        v.Icon(children=["mdi-map-marker"]),
                    ],
                ),
            ],
        ),
        v.Responsive(
            id="hide-on-scroll-example",
            class_="overflow-y-auto",
            max_height="600",
            children=[
                v.Responsive(height="1500"),
            ],
        ),
    ],
)
