import pyvuetify as v

v.Layout(
    style_="height: 56px;",
    children=[
        v.BottomNavigation(
            v_model="value",
            # JS expression, needs manual conversion
            bg_color="color",
            mode="shift",
            children=[
                v.Btn(
                    children=[
                        v.Icon(children=["mdi-television-play"]),
                        v.Html(
                            tag="span",
                            children=["Video"],
                        ),
                    ],
                ),
                v.Btn(
                    children=[
                        v.Icon(children=["mdi-music-note"]),
                        v.Html(
                            tag="span",
                            children=["Music"],
                        ),
                    ],
                ),
                v.Btn(
                    children=[
                        v.Icon(children=["mdi-book"]),
                        v.Html(
                            tag="span",
                            children=["Book"],
                        ),
                    ],
                ),
                v.Btn(
                    children=[
                        v.Icon(children=["mdi-image"]),
                        v.Html(
                            tag="span",
                            children=["Image"],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
