import pyvuetify as v

v.Container(
    children=[
        v.Row(
            class_="flex-child text-title-small",
            children=[
                v.Col(
                    class_="d-flex",
                    cols="12",
                    md="4",
                    children=[
                        v.Sheet(
                            class_="d-flex",
                            color="grey-lighten-3",
                            height="424",
                            children=[
                                v.Html(
                                    tag="sheet-footer",
                                    children=["#1: (3r x 2c)"],
                                ),
                            ],
                        ),
                    ],
                ),
                v.Col(
                    class_="d-flex",
                    cols="12",
                    md="4",
                    children=[
                        v.Row(
                            class_="ma-n3",
                            children=[
                                v.Col(
                                    cols="6",
                                    children=[
                                        v.Sheet(
                                            class_="d-flex",
                                            color="green-lighten-3",
                                            height="150",
                                            children=[
                                                v.Html(
                                                    tag="sheet-footer",
                                                    children=["#2: (1r x 1c)"],
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                                v.Col(
                                    cols="6",
                                    children=[
                                        v.Sheet(
                                            class_="d-flex",
                                            color="yellow-lighten-3",
                                            height="150",
                                            children=[
                                                v.Html(
                                                    tag="sheet-footer",
                                                    children=["#3: (1r x 1c)"],
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                                v.Col(
                                    cols="12",
                                    children=[
                                        v.Sheet(
                                            class_="d-flex",
                                            color="red-lighten-3",
                                            height="250",
                                            children=[
                                                v.Html(
                                                    tag="sheet-footer",
                                                    children=["#5: (2r x 2c)"],
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
                v.Col(
                    cols="6",
                    md="2",
                    children=[
                        v.Sheet(
                            class_="d-flex",
                            color="teal-lighten-3",
                            height="300",
                            children=[
                                v.Html(
                                    tag="sheet-footer",
                                    children=["#4: (2r x 1c)"],
                                ),
                            ],
                        ),
                    ],
                ),
                v.Col(
                    class_="d-flex",
                    cols="6",
                    md="2",
                    children=[
                        v.Sheet(
                            class_="d-flex mt-auto",
                            color="purple-lighten-3",
                            height="300",
                            children=[
                                v.Html(
                                    tag="sheet-footer",
                                    children=["#6: (2r x 1c)"],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
