import ipyvuetify as v

v.Card(
    flat=True,
    children=[
        v.CardText(
            children=[
                v.Container(
                    fluid=True,
                    class_="pa-0",
                    children=[
                        v.Row(
                            children=[
                                v.Col(cols=12, children=[v.Html(tag="p", children=["Normal"])]),
                                v.Col(
                                    cols=12,
                                    sm=3,
                                    children=[
                                        v.Btn(
                                            icon=True,
                                            color="pink",
                                            children=[v.Icon(children=["mdi-heart"])],
                                        )
                                    ],
                                ),
                                v.Col(
                                    cols=12,
                                    sm=3,
                                    children=[
                                        v.Btn(
                                            icon=True,
                                            color="indigo",
                                            children=[v.Icon(children=["mdi-star"])],
                                        )
                                    ],
                                ),
                                v.Col(
                                    cols=12,
                                    sm=3,
                                    children=[
                                        v.Btn(
                                            icon=True,
                                            color="green",
                                            children=[v.Icon(children=["mdi-cached"])],
                                        )
                                    ],
                                ),
                                v.Col(
                                    cols=12,
                                    sm=3,
                                    children=[
                                        v.Btn(
                                            icon=True,
                                            color="deep-orange",
                                            children=[v.Icon(children=["mdi-thumb-up"])],
                                        )
                                    ],
                                ),
                            ]
                        ),
                        v.Row(
                            class_="mt-12",
                            children=[
                                v.Col(cols=12, children=[v.Html(tag="p", children=["Disabled"])]),
                                v.Col(
                                    cols=12,
                                    sm=3,
                                    children=[
                                        v.Btn(
                                            icon=True,
                                            disabled=True,
                                            children=[v.Icon(children=["mdi-heart"])],
                                        )
                                    ],
                                ),
                                v.Col(
                                    cols=12,
                                    sm=3,
                                    children=[
                                        v.Btn(
                                            icon=True,
                                            disabled=True,
                                            children=[v.Icon(children=["mdi-star"])],
                                        )
                                    ],
                                ),
                                v.Col(
                                    cols=12,
                                    sm=3,
                                    children=[
                                        v.Btn(
                                            icon=True,
                                            disabled=True,
                                            children=[v.Icon(children=["mdi-cached"])],
                                        )
                                    ],
                                ),
                                v.Col(
                                    cols=12,
                                    sm=3,
                                    children=[
                                        v.Btn(
                                            icon=True,
                                            disabled=True,
                                            children=[v.Icon(children=["mdi-thumb-up"])],
                                        )
                                    ],
                                ),
                            ],
                        ),
                    ],
                )
            ]
        )
    ],
)
