import ipyvuetify as v

v.Container(
    fluid=True,
    class_="pa-0",
    children=[
        v.Row(
            align="center",
            children=[
                v.Col(
                    cols=12,
                    sm=6,
                    children=[
                        v.Html(
                            tag="div",
                            class_="text-center",
                            children=[
                                v.Html(
                                    tag="div",
                                    class_="my-2",
                                    children=[
                                        v.Btn(
                                            x_small=True,
                                            color="secondary",
                                            dark=True,
                                            children=["Extra small Button"],
                                        )
                                    ],
                                ),
                                v.Html(
                                    tag="div",
                                    class_="my-2",
                                    children=[
                                        v.Btn(
                                            small=True,
                                            color="primary",
                                            dark=True,
                                            children=["Small Button"],
                                        )
                                    ],
                                ),
                                v.Html(
                                    tag="div",
                                    class_="my-2",
                                    children=[
                                        v.Btn(
                                            color="warning", dark=True, children=["Normal Button"]
                                        )
                                    ],
                                ),
                                v.Html(
                                    tag="div",
                                    class_="my-2",
                                    children=[
                                        v.Btn(
                                            large=True,
                                            color="error",
                                            dark=True,
                                            children=["Large Button"],
                                        )
                                    ],
                                ),
                                v.Html(
                                    tag="div",
                                    class_="my-2",
                                    children=[
                                        v.Btn(
                                            x_large=True,
                                            color="success",
                                            dark=True,
                                            children=["Extra large Button"],
                                        )
                                    ],
                                ),
                            ],
                        )
                    ],
                ),
                v.Col(
                    cols=12,
                    sm=6,
                    children=[
                        v.Html(
                            tag="div",
                            class_="text-center",
                            children=[
                                v.Html(
                                    tag="div",
                                    class_="my-2",
                                    children=[
                                        v.Btn(
                                            fab=True,
                                            x_small=True,
                                            color="secondary",
                                            dark=True,
                                            children=[v.Icon(children=["mdi-television"])],
                                        )
                                    ],
                                ),
                                v.Html(
                                    tag="div",
                                    class_="my-2",
                                    children=[
                                        v.Btn(
                                            fab=True,
                                            small=True,
                                            color="primary",
                                            dark=True,
                                            children=[v.Icon(children=["mdi-pencil"])],
                                        )
                                    ],
                                ),
                                v.Html(
                                    tag="div",
                                    class_="my-2",
                                    children=[
                                        v.Btn(
                                            fab=True,
                                            color="warning",
                                            dark=True,
                                            children=[v.Icon(children=["mdi-account-circle"])],
                                        )
                                    ],
                                ),
                                v.Html(
                                    tag="div",
                                    class_="my-2",
                                    children=[
                                        v.Btn(
                                            fab=True,
                                            large=True,
                                            color="error",
                                            dark=True,
                                            children=[v.Icon(children=["mdi-alarm"])],
                                        )
                                    ],
                                ),
                                v.Html(
                                    tag="div",
                                    class_="my-2",
                                    children=[
                                        v.Btn(
                                            fab=True,
                                            x_large=True,
                                            color="success",
                                            dark=True,
                                            children=[v.Icon(children=["mdi-domain"])],
                                        )
                                    ],
                                ),
                            ],
                        )
                    ],
                ),
            ],
        )
    ],
)
