import pyvuetify as v

v.Container(
    fluid=True,
    children=[
        v.Html(
            tag="div",
            class_="d-flex justify-center align-center ga-4 mb-6",
            children=[
                v.BtnToggle(
                    v_model="variant",
                    variant="outlined",
                    divided=True,
                    mandatory=True,
                    children=[
                        v.Btn(
                            value="default",
                            children=["Default"],
                        ),
                        v.Btn(
                            value="inset",
                            children=["Inset"],
                        ),
                        v.Btn(
                            value="material",
                            children=["Material"],
                        ),
                        v.Btn(
                            value="square",
                            children=["Square"],
                        ),
                    ],
                ),
                v.Checkbox(
                    v_model="icons",
                    label="Icons",
                    hide_details=True,
                ),
            ],
        ),
        v.Row(
            children=[
                v.Col(
                    cols="6",
                    children=[
                        v.Switch(
                            model_value=True,
                            color="primary",
                            label="on",
                        ),
                    ],
                ),
                v.Col(
                    cols="6",
                    children=[
                        v.Switch(
                            model_value=False,
                            color="primary",
                            label="off",
                        ),
                    ],
                ),
            ],
        ),
        v.Row(
            children=[
                v.Col(
                    cols="6",
                    children=[
                        v.Switch(
                            model_value=True,
                            color="primary",
                            label="on disabled",
                            disabled=True,
                        ),
                    ],
                ),
                v.Col(
                    cols="6",
                    children=[
                        v.Switch(
                            model_value=False,
                            color="primary",
                            label="off disabled",
                            disabled=True,
                        ),
                    ],
                ),
            ],
        ),
        v.Row(
            children=[
                v.Col(
                    cols="6",
                    children=[
                        v.Switch(
                            model_value=True,
                            label="on loading",
                            loading="warning",
                        ),
                    ],
                ),
                v.Col(
                    cols="6",
                    children=[
                        v.Switch(
                            model_value=False,
                            label="off loading",
                            loading="warning",
                        ),
                    ],
                ),
            ],
        ),
    ],
)
