import pyvuetify as v

v.Container(
    children=[
        v.Row(
            children=[
                v.Col(
                    cols="12",
                    md="4",
                    sm="4",
                    children=[
                        v.Html(
                            tag="h5",
                            class_="my-0",
                            children=["Default"],
                        ),
                        v.NumberInput(control_variant="default"),
                    ],
                ),
                v.Col(
                    cols="12",
                    md="4",
                    sm="4",
                    children=[
                        v.Html(
                            tag="h5",
                            class_="my-0",
                            children=["Stacked"],
                        ),
                        v.NumberInput(control_variant="stacked"),
                    ],
                ),
                v.Col(
                    cols="12",
                    md="4",
                    sm="4",
                    children=[
                        v.Html(
                            tag="h5",
                            class_="my-0",
                            children=["Split"],
                        ),
                        v.NumberInput(control_variant="split"),
                    ],
                ),
                v.Col(
                    cols="12",
                    md="4",
                    sm="4",
                    children=[
                        v.Html(
                            tag="h5",
                            class_="my-0",
                            children=["Hidden"],
                        ),
                        v.NumberInput(control_variant="hidden"),
                    ],
                ),
            ],
        ),
    ],
)
