import pyvuetify as v

v.Container(
    children=[
        v.Row(
            children=[
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Html(
                            tag="h5",
                            class_="my-0",
                            children=["Default"],
                        ),
                        v.NumberInput(
                            control_variant="default",
                            inset=True,
                        ),
                    ],
                ),
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Html(
                            tag="h5",
                            class_="my-0",
                            children=["Stacked"],
                        ),
                        v.NumberInput(
                            control_variant="stacked",
                            inset=True,
                        ),
                    ],
                ),
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Html(
                            tag="h5",
                            class_="my-0",
                            children=["Split"],
                        ),
                        v.NumberInput(
                            control_variant="split",
                            inset=True,
                        ),
                    ],
                ),
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Html(
                            tag="h5",
                            class_="my-0",
                            children=["Hide-input"],
                        ),
                        v.NumberInput(
                            hide_input=True,
                            inset=True,
                        ),
                    ],
                ),
            ],
        ),
    ],
)
