import pyvuetify as v

v.Html(
    tag="div",
    class_="text-center",
    children=[
        v.ProgressCircular(
            size=50,
            color="primary",
            indeterminate=True,
        ),
        v.ProgressCircular(
            width=3,
            color="red",
            indeterminate=True,
        ),
        v.ProgressCircular(
            size=70,
            width=7,
            color="purple",
            indeterminate=True,
        ),
        v.ProgressCircular(
            width=3,
            color="green",
            indeterminate=True,
        ),
        v.ProgressCircular(
            size=50,
            color="amber",
            indeterminate=True,
        ),
    ],
)
