import ipyvuetify as v

states = [
    "Alabama",
    "Alaska",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Federated States of Micronesia",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Marshall Islands",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Northern Mariana Islands",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Palau",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virgin Island",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]

v.Container(
    fluid=True,
    children=[
        v.Row(
            align="center",
            children=[
                v.Col(
                    cols=6,
                    children=[
                        v.Subheader(children=["Multiple select"]),
                    ],
                ),
                v.Col(
                    cols=6,
                    children=[
                        v.Select(
                            v_model=["California", "New York"],
                            items=states,
                            label="Select",
                            multiple=True,
                            menu_props={"maxHeight": "400"},
                        ),
                    ],
                ),
                v.Col(
                    cols=6,
                    children=[
                        v.Subheader(children=["Multiple with chips"]),
                    ],
                ),
                v.Col(
                    cols=6,
                    children=[
                        v.Select(
                            v_model=["Texas", "Florida"],
                            items=states,
                            chips=True,
                            label="Select",
                            multiple=True,
                        ),
                    ],
                ),
            ],
        ),
    ],
)
