import pyvuetify as v

v.Row(
    children=[
        v.Col(
            cols="12",
            offset_sm="3",
            sm="6",
            children=[
                v.Card(
                    height="200px",
                    children=[
                        v.CardTitle(
                            class_="bg-blue d-flex align-center",
                            children=[
                                v.Html(
                                    tag="span",
                                    class_="text-headline-small",
                                    children=["Menu"],
                                ),
                                v.Spacer(),
                                v.Menu(
                                    children=[
                                        v.Html(
                                            tag="template",
                                            children=[
                                                v.Btn(
                                                    icon="mdi-dots-vertical",
                                                    variant="text",
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
