import ipyvuetify as v

v.Container(
    fluid=True,
    children=[
        v.Row(
            children=[
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Textarea(
                            class_="mx-2",
                            label="prepend-icon",
                            rows="1",
                            prepend_icon="mdi-comment",
                        )
                    ],
                ),
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Textarea(
                            append_icon="mdi-comment",
                            class_="mx-2",
                            label="append-icon",
                            rows="1",
                        )
                    ],
                ),
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Textarea(
                            prepend_inner_icon="mdi-comment",
                            class_="mx-2",
                            label="prepend-inner-icon",
                            rows="1",
                        )
                    ],
                ),
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Textarea(
                            append_outer_icon="mdi-comment",
                            class_="mx-2",
                            label="append-outer-icon",
                            rows="1",
                        )
                    ],
                ),
            ],
        )
    ],
)
