import pyvuetify as v

v.Container(
    children=[
        v.Row(
            children=[
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Textarea(
                            class_="mx-2",
                            label="prepend-icon",
                            prepend_icon="mdi-comment",
                            rows="1",
                        ),
                    ],
                ),
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Textarea(
                            append_icon="mdi-comment",
                            class_="mx-2",
                            label="append-icon",
                            rows="1",
                        ),
                    ],
                ),
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Textarea(
                            class_="mx-2",
                            label="prepend-inner-icon",
                            prepend_inner_icon="mdi-comment",
                            rows="1",
                        ),
                    ],
                ),
                v.Col(
                    cols="12",
                    sm="6",
                    children=[
                        v.Textarea(
                            append_inner_icon="mdi-comment",
                            class_="mx-2",
                            label="append-inner-icon",
                            rows="1",
                        ),
                    ],
                ),
            ],
        ),
    ],
)
