import pyvuetify as v

v.Card(
    class_="mx-auto",
    max_width="400",
    children=[
        v.Layout(
            children=[
                v.SystemBar(
                    color="pink-darken-2",
                    children=[
                        v.Spacer(),
                        v.Icon(children=["mdi-window-minimize"]),
                        v.Icon(children=["mdi-window-maximize"]),
                        v.Icon(children=["mdi-close"]),
                    ],
                ),
                v.AppBar(
                    color="pink",
                    children=[
                        v.AppBarNavIcon(),
                        v.ToolbarTitle(children=["My Music"]),
                        v.Btn(icon="mdi-magnify"),
                    ],
                ),
                v.Main(
                    children=[
                        v.Container(
                            children=[
                                v.Row(
                                    density="comfortable",
                                    children=[
                                        v.Col(
                                            cols="12",
                                            children=[
                                                v.Card(
                                                    color="#385F73",
                                                    children=[
                                                        v.CardTitle(
                                                            class_="text-headline-small",
                                                            children=["Unlimited music now"],
                                                        ),
                                                        v.CardSubtitle(
                                                            children=[
                                                                (
                                                                    "Listen to your favorite "
                                                                    "artists and albums whenever "
                                                                    "and wherever, online and "
                                                                    "offline."
                                                                ),
                                                            ],
                                                        ),
                                                        v.CardActions(
                                                            children=[
                                                                v.Btn(
                                                                    text="Listen Now",
                                                                    variant="text",
                                                                ),
                                                            ],
                                                        ),
                                                    ],
                                                ),
                                            ],
                                        ),
                                        v.Col(
                                            cols="12",
                                            children=[
                                                v.Card(
                                                    color="#1F7087",
                                                    children=[
                                                        v.Html(
                                                            tag="div",
                                                            class_=("d-flex flex-no-wrap justify-space-between"),
                                                            children=[
                                                                v.Html(
                                                                    tag="div",
                                                                    children=[
                                                                        v.CardTitle(
                                                                            class_="text-headline-small",
                                                                            children=["Supermodel"],
                                                                        ),
                                                                        v.CardSubtitle(children=["Foster the People"]),
                                                                        v.CardActions(
                                                                            children=[
                                                                                v.Btn(
                                                                                    class_="ms-2",
                                                                                    size="small",
                                                                                    text="START RADIO",
                                                                                    variant="outlined",
                                                                                ),
                                                                            ],
                                                                        ),
                                                                    ],
                                                                ),
                                                                v.Avatar(
                                                                    class_="ma-3",
                                                                    rounded="0",
                                                                    size="125",
                                                                    children=[
                                                                        v.Img(
                                                                            src="https://cdn.vuetifyjs.com/images/cards/foster.jpg"
                                                                        ),
                                                                    ],
                                                                ),
                                                            ],
                                                        ),
                                                    ],
                                                ),
                                            ],
                                        ),
                                        v.Col(
                                            cols="12",
                                            children=[
                                                v.Card(
                                                    color="#952175",
                                                    children=[
                                                        v.Html(
                                                            tag="div",
                                                            class_=("d-flex flex-no-wrap justify-space-between"),
                                                            children=[
                                                                v.Html(
                                                                    tag="div",
                                                                    children=[
                                                                        v.CardTitle(
                                                                            class_="text-headline-small",
                                                                            children=["Halcyon Days"],
                                                                        ),
                                                                        v.CardSubtitle(children=["Ellie Goulding"]),
                                                                        v.CardActions(
                                                                            children=[
                                                                                v.Btn(
                                                                                    class_="ms-2",
                                                                                    icon="mdi-play",
                                                                                    variant="text",
                                                                                ),
                                                                            ],
                                                                        ),
                                                                    ],
                                                                ),
                                                                v.Avatar(
                                                                    class_="ma-3",
                                                                    rounded="0",
                                                                    size="125",
                                                                    children=[
                                                                        v.Img(
                                                                            src="https://cdn.vuetifyjs.com/images/cards/halcyon.png"
                                                                        ),
                                                                    ],
                                                                ),
                                                            ],
                                                        ),
                                                    ],
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
