import pyvuetify as v

v.Html(
    tag="div",
    children=[
        v.Layout(
            style_="height: 50px",
            children=[
                v.SystemBar(
                    color="primary",
                    children=[
                        v.Icon(
                            class_="ms-2",
                            icon="mdi-wifi-strength-4",
                        ),
                        v.Icon(
                            class_="ms-2",
                            icon="mdi-signal-cellular-outline",
                        ),
                        v.Icon(
                            class_="ms-2",
                            icon="mdi-battery",
                        ),
                        v.Html(
                            tag="span",
                            class_="ms-2",
                            children=["08:30"],
                        ),
                    ],
                ),
            ],
        ),
        v.Layout(
            style_="height: 50px",
            children=[
                v.SystemBar(
                    color="red-lighten-2",
                    children=[
                        v.Icon(
                            class_="ms-2",
                            icon="mdi-wifi-strength-2",
                        ),
                        v.Icon(
                            class_="ms-2",
                            icon="mdi-signal-cellular-outline",
                        ),
                        v.Icon(
                            class_="ms-2",
                            icon="mdi-battery",
                        ),
                        v.Html(
                            tag="span",
                            class_="ms-2",
                            children=["18:30"],
                        ),
                    ],
                ),
            ],
        ),
        v.Layout(
            style_="height: 50px",
            children=[
                v.SystemBar(
                    color="indigo-darken-2",
                    children=[
                        v.Icon(
                            class_="ms-2",
                            icon="mdi-wifi-strength-3",
                        ),
                        v.Icon(
                            class_="ms-2",
                            icon="mdi-signal-cellular-outline",
                        ),
                        v.Icon(
                            class_="ms-2",
                            icon="mdi-battery",
                        ),
                        v.Html(
                            tag="span",
                            class_="ms-2",
                            children=["13:24"],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
