import pyvuetify as v

v.Container(
    children=[
        v.Row(
            children=[
                v.Col(
                    cols="12",
                    md="4",
                    children=[
                        v.Btn(
                            class_="my-4",
                            block=True,
                            children=["null"],
                        ),
                        v.Btn(
                            class_="my-4",
                            block=True,
                            children=["hex"],
                        ),
                        v.Btn(
                            class_="my-4",
                            block=True,
                            children=["hexa"],
                        ),
                        v.Btn(
                            class_="my-4",
                            block=True,
                            children=["rgba"],
                        ),
                        v.Btn(
                            class_="my-4",
                            block=True,
                            children=["hsla"],
                        ),
                        v.Btn(
                            class_="my-4",
                            block=True,
                            children=["hsva"],
                        ),
                    ],
                ),
                v.Col(
                    class_="d-flex justify-center",
                    children=[
                        v.ColorPicker(v_model="color"),
                    ],
                ),
                v.Col(
                    cols="12",
                    md="4",
                    children=[
                        v.Sheet(
                            class_="pa-4",
                            children=[
                                v.Html(
                                    tag="pre",
                                    children=["{{ color }}"],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
