import pyvuetify as v

v.Card(
    class_="mx-auto",
    max_width="375",
    children=[
        v.Img(
            class_="text-white",
            height="300px",
            src="https://cdn.vuetifyjs.com/images/lists/ali.png",
            cover=True,
            children=[
                v.Html(
                    tag="div",
                    class_="d-flex flex-column h-100",
                    children=[
                        v.CardTitle(
                            class_="d-flex ga-2 px-2",
                            children=[
                                v.Btn(
                                    icon="mdi-chevron-left",
                                    variant="text",
                                ),
                                v.Spacer(),
                                v.Btn(
                                    icon="mdi-pencil",
                                    variant="text",
                                ),
                                v.Btn(
                                    icon="mdi-dots-vertical",
                                    variant="text",
                                ),
                            ],
                        ),
                        v.Spacer(),
                        v.CardTitle(
                            class_="pb-6 text-center",
                            children=[
                                v.Html(
                                    tag="div",
                                    class_="text-headline-large",
                                    children=["Ali Conners"],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
        v.List(
            lines="two",
            children=[
                v.ListItem(
                    children=[
                        v.Html(
                            tag="template",
                            children=[
                                v.Avatar(
                                    children=[
                                        v.Icon(
                                            color="indigo",
                                            icon="mdi-phone",
                                        ),
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
