import pyvuetify as v

v.Card(
    class_="mx-auto",
    width="256",
    children=[
        v.Layout(
            children=[
                v.NavigationDrawer(
                    absolute=True,
                    permanent=True,
                    children=[
                        v.List(
                            children=[
                                v.ListItem(
                                    prepend_avatar="https://cdn.vuetifyjs.com/images/john.png",
                                    subtitle="john@google.com",
                                    title="John Leider",
                                    children=[
                                        v.Html(
                                            tag="template",
                                            children=[
                                                v.Btn(
                                                    icon="mdi-menu-down",
                                                    size="small",
                                                    variant="text",
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
