import pyvuetify as v

v.Card(
    class_="mx-auto",
    width="300",
    children=[
        v.List(
            v_model_opened="open",
            children=[
                v.ListItem(
                    prepend_icon="mdi-home",
                    title="Home",
                ),
                v.ListGroup(
                    value="Users",
                    children=[
                        v.Html(
                            tag="template",
                            children=[
                                v.ListItem(
                                    prepend_icon="mdi-account-circle",
                                    title="Users",
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
