import pyvuetify as v

v.Row(
    children=[
        v.Col(
            children=[
                v.Sheet(
                    height="400",
                    children=[
                        v.Calendar(
                            color="primary",
                            type="day",
                            children=[
                                v.Html(
                                    tag="template",
                                    children=[
                                        v.Html(
                                            tag="div",
                                            class_="text-center",
                                            children=["Today"],
                                        ),
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
