import pyvuetify as v

v.Card(
    class_="mx-auto overflow-hidden",
    max_width="600",
    children=[
        v.Row(
            children=[
                v.Col(
                    class_="d-flex",
                    cols="6",
                    children=[
                        v.Img(
                            src="https://cdn.vuetifyjs.com/images/ratings/fortnite1.png",
                        ),
                    ],
                ),
                v.Col(
                    cols="6",
                    children=[
                        v.Container(
                            class_="pa-0 ps-2 my-n1",
                            children=[
                                v.Row(
                                    children=[
                                        v.Col(
                                            class_="d-flex",
                                            cols="7",
                                            children=[
                                                v.Img(
                                                    src="https://cdn.vuetifyjs.com/images/ratings/fortnite2.png",
                                                ),
                                            ],
                                        ),
                                        v.Col(
                                            class_="d-flex",
                                            cols="5",
                                            children=[
                                                v.Img(
                                                    src="https://cdn.vuetifyjs.com/images/ratings/fortnite3.png",
                                                ),
                                            ],
                                        ),
                                        v.Col(
                                            class_="d-flex",
                                            cols="5",
                                            children=[
                                                v.Img(
                                                    src="https://cdn.vuetifyjs.com/images/ratings/fortnite4.png",
                                                ),
                                            ],
                                        ),
                                        v.Col(
                                            class_="d-flex",
                                            cols="7",
                                            children=[
                                                v.Img(
                                                    src="https://cdn.vuetifyjs.com/images/ratings/fortnite5.png",
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
        v.CardTitle(
            class_="align-start",
            children=[
                v.Html(
                    tag="div",
                    children=[
                        v.Html(
                            tag="span",
                            class_="text-headline-small",
                            children=["FORTNITE"],
                        ),
                        v.Html(
                            tag="div",
                            class_="text-grey font-weight-light",
                            children=["Video game"],
                        ),
                    ],
                ),
                v.Spacer(),
                v.Dialog(
                    v_model="dialog",
                    width="400",
                    children=[
                        v.Html(
                            tag="template",
                            children=[
                                v.Icon(icon="mdi-share-variant"),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
