import pyvuetify as v

v.Html(
    tag="div",
    class_="text-center",
    children=[
        v.Chip(
            class_="ma-2",
            color="indigo",
            prepend_icon="mdi-account-circle",
            children=["Mike"],
        ),
        v.Chip(
            append_icon="mdi-star",
            class_="ma-2",
            color="orange",
            children=["Premium"],
        ),
        v.Chip(
            append_icon="mdi-cake-variant",
            class_="ma-2",
            color="primary",
            children=["1 Year"],
        ),
        v.Chip(
            class_="ma-2",
            color="green",
            children=[
                v.Html(
                    tag="template",
                    children=[
                        v.Avatar(
                            class_="green-darken-4",
                            children=["1"],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
