import pyvuetify as v

v.Html(
    tag="div",
    class_="text-center",
    children=[
        v.Chip(
            class_="ma-2",
            label=True,
            children=["Label"],
        ),
        v.Chip(
            class_="ma-2",
            color="pink",
            label=True,
            children=[
                v.Icon(
                    icon="mdi-label",
                    start=True,
                ),
                "Tags",
            ],
        ),
        v.Chip(
            class_="ma-2",
            color="primary",
            label=True,
            children=[
                v.Icon(
                    icon="mdi-account-circle-outline",
                    start=True,
                ),
                "John Leider",
            ],
        ),
        v.Chip(
            class_="ma-2",
            color="cyan",
            closable=True,
            label=True,
            children=[
                v.Icon(
                    icon="mdi-twitter",
                    start=True,
                ),
                "New Tweets",
            ],
        ),
    ],
)
