import pyvuetify as v

v.Container(
    class_="text-center",
    fluid=True,
    children=[
        v.Row(
            class_="flex justify-space-between",
            children=[
                v.Col(
                    cols="12",
                    children=[
                        v.Btn(children=["toggle"]),
                    ],
                ),
                v.Col(
                    class_="mt-12",
                    cols="12",
                    children=[
                        v.Tooltip(
                            v_model="show",
                            location="top",
                            children=[
                                v.Html(
                                    tag="template",
                                    children=[
                                        v.Btn(
                                            icon=True,
                                            children=[
                                                v.Icon(
                                                    color="grey-lighten-1",
                                                    children=["mdi-cart"],
                                                ),
                                            ],
                                        ),
                                    ],
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
