import pyvuetify as v

v.Html(
    tag="div",
    class_="text-center",
    children=[
        v.Html(
            tag="div",
            children=[
                v.Btn(
                    class_="ma-2",
                    color="primary",
                    children=[
                        "Accept",
                        v.Icon(
                            icon="mdi-checkbox-marked-circle",
                            end=True,
                        ),
                    ],
                ),
                v.Btn(
                    class_="ma-2",
                    color="red",
                    children=[
                        "Decline",
                        v.Icon(
                            icon="mdi-cancel",
                            end=True,
                        ),
                    ],
                ),
                v.Btn(
                    class_="ma-2",
                    children=[
                        v.Icon(
                            icon="mdi-minus-circle",
                            start=True,
                        ),
                        "Cancel",
                    ],
                ),
            ],
        ),
        v.Html(
            tag="div",
            children=[
                v.Btn(
                    class_="ma-2",
                    color="orange-darken-2",
                    children=[
                        v.Icon(
                            icon="mdi-arrow-left",
                            start=True,
                        ),
                        "Back",
                    ],
                ),
                v.Btn(
                    class_="ma-2",
                    color="purple",
                    icon="mdi-wrench",
                ),
                v.Btn(
                    class_="ma-2",
                    color="indigo",
                    icon="mdi-cloud-upload",
                ),
            ],
        ),
        v.Html(
            tag="div",
            children=[
                v.Btn(
                    class_="ma-2",
                    color="blue-lighten-2",
                    icon="mdi-thumb-up",
                    variant="text",
                ),
                v.Btn(
                    class_="ma-2",
                    color="red-lighten-2",
                    icon="mdi-thumb-down",
                    variant="text",
                ),
            ],
        ),
    ],
)
