import pyvuetify as v

v.Card(
    height="300",
    image="https://cdn.vuetifyjs.com/images/toolbar/map.jpg",
    border=True,
    flat=True,
    children=[
        v.Html(
            tag="template",
            children=[
                v.Toolbar(
                    rounded="lg",
                    border=True,
                    floating=True,
                    children=[
                        v.Html(
                            tag="div",
                            class_="px-4",
                            children=[
                                v.TextField(
                                    density="compact",
                                    placeholder="Search",
                                    prepend_inner_icon="mdi-magnify",
                                    variant="solo",
                                    width="200",
                                    flat=True,
                                    hide_details=True,
                                    single_line=True,
                                ),
                            ],
                        ),
                        v.Html(
                            tag="template",
                            children=[
                                v.Btn(
                                    color="medium-emphasis",
                                    density="comfortable",
                                    icon="mdi-crosshairs-gps",
                                ),
                                v.Btn(
                                    class_="ms-1",
                                    color="medium-emphasis",
                                    density="comfortable",
                                    icon="mdi-dots-vertical",
                                ),
                            ],
                        ),
                    ],
                ),
            ],
        ),
    ],
)
